#!/usr/bin/env python3
import cgi, os
import cgitb; cgitb.enable()
form = cgi.FieldStorage()


def printForm():
    form_template_file=open ("templates/form.html", "r")
    form_template=form_template_file.read()

    print("Content-Type: text/html\n\n")
    IDs=["pippo","pluto"] #FIXME: fetch those from tom's script
    BadIDs=["zio paperone","zio paperino"]
    options=""
    for i in IDs :
      options+='<option value="%s">%s</option>' %(i,i)

    for i in BadIDs :
      options+='<option style="color: #cccccc"  value="%s">%s</option>' %(i,i)
    print(form_template.format(options=options))


def receiveAndSaveToGoogleSheet():
    print("Content-Type: text/html\n\n")
    file1 = form['file1']
    if file1.filename :
        open('/dev/null', 'wb').write(file1.file.read()) #FIXME: do something better than writing to dev null
    
    print("Test id is %s, I better write that to google sheet<bR>"%(form.getvalue("TestID")))
    print("Upload was ok")

def main():
    if "submit" in form.keys():
        receiveAndSaveToGoogleSheet()
    else:
        printForm()

if __name__ == '__main__':
    main()

