#!/usr/bin/env python3
import cgi, os
import cgitb; cgitb.enable()
form = cgi.FieldStorage()

#for gsheet
import pickle
import os.path
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
import sys
import os

from gsheet_actions_newtemplate import *


def printForm(opU,opF):
    form_template_file=open ("templates/form.html", "r")
    form_template=form_template_file.read()

    print("Content-Type: text/html\n\n")
    options=""
    for i in opU.keys() :
      options+='<option value="%s">%s</option>' %(i,i)

    for i in opF.keys() :
        options+='<option style="color: #cccccc; background-color:#FF0000"  value="%s">%s</option>' %(i,i)

    options_Campaign=""
    options_TestID=[]
    for i in opU.keys() :
        options_Campaign+='<option value="%s">%s</option>' %(i,i)
        options_TestID.append("")
        for j in opU[i].keys() :
            myvalue="%s"%(j)
            options_TestID[-1]+="<option value=\'%s\'>%s</option>"%(myvalue,myvalue)
        
    print(form_template.format(options_Campaign=options_Campaign, options=options, options_TestID=options_TestID))


def receiveAndSaveToGoogleSheet(dict_ids, col_simulator_filename, col_mvm_filename, service, SAMPLE_SPREADSHEET_ID):
    print("Content-Type: text/html\n\n")
    testID = form.getvalue("TestID")
    file_simulator = form['file1']
    file_simulator_2 = form['file2']
    file_mvm = form['file3']
    #
    # i issue an error if the first two are different suffix apart
    #
    if (os.path.splitext(file_simulator.filename)[0] != os.path.splitext(file_simulator_2.filename)[0]):
        print ("ERROR! The two simulator files should have the same name apart from the suffix. I got ",file_simulator.filename, file_simulator_2.filename)
        sys.exit(3)
        filename_simulator_no_suffix = os.path.splitext(file_simulator.filename)[0]
#
# I have to refuse doing anything if sfirst and second are differen
#    if file_simulator.filename :
#        open('/dev/null', 'wb').write(file_simulator.file.read()) #FIXME: do something better than writing to dev null
#    if file_mvm.filename :
#        open('/dev/null', 'wb').write(file_mvm.file.read()) #FIXME: do something better than writing to dev null
#    if file_simulator_2xs.filename :
#        open('/dev/null', 'wb').write(file_simulator_2.file.read()) #FIXME: do something better than writing to dev null
    
    print("Test id is %s, I better write that to google sheet<bR>"%(testID))
    print("Upload was ok")
    #
    # now I fix them in the gsheet
    #
    print("Filling the gsheet")
    print ("Test ID = " ,testID )
    print ("F_SIM = " , file_simulator.filename)
    print ("F_SI2 = " ,file_simulator_2.filename )
    print ("F_MVM = " ,file_mvm.filename )

# simulator 1 and 2 ....
    insert_single_cell(dict_ids[testID], col_simulator_filename,filename_simulator_no_suffix, service, SAMPLE_SPREADSHEET_ID )
# mvm
    insert_single_cell(dict_ids[testID], col_mvm_filename,file_simulator.filename, service, SAMPLE_SPREADSHEET_ID )


def main():
    # The ID and range of a sample spreadsheet.
    SAMPLE_SPREADSHEET_ID = '1AQXgqCKNAuCCDGffi9QU_v_9tOP97qYQNyxx9L6pWRA'
    Suffix_SAMPLE_RANGE_NAME = '!A:AR'
    service  = initGsheet(SAMPLE_SPREADSHEET_ID)

    (optionmap,opF,opU) = getIDsForm(SAMPLE_SPREADSHEET_ID,Suffix_SAMPLE_RANGE_NAME,service, VERB=False)


    if "submit" in form.keys():
        receiveAndSaveToGoogleSheet(dict_ids, col_simulator_filename, col_mvm_filename, service, SAMPLE_SPREADSHEET_ID)
    else:
        printForm(opU,opF)

if __name__ == '__main__':
    main()

